### ISSUE TITLE
The trained model cannot be extracted

### ISSUE THREAD

**Issue by amiltonwong** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#1]
Hi, authors,

After I downloaded the provided trained model in [gz](https://3d.bk.tudelft.nl/opendata/sum/1.0/trained_model/SUM_Helsinki_C6_trained_model/trained_model.gz) file, and execute the command `tar zxvf trained_model.gz`, I got the following error:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Is that something wrong with the trained_model.gz file? Would you provide a corrected one? (and saved in zip format is better)

Thanks

**Comment by WeixiaoGao** [comment]
Hi, the trained model is not being used for direct decompression. You can read it directly with the code provided by setting the configuration file to 'Test_config'. And it depends on the Boost libraries [Serialization](https://www.boost.org/libs/serialization) and [IO Streams](https://www.boost.org/libs/iostreams) (compiled with the GZIP dependency). For more information please refer to the [CGAL classification](https://doc.cgal.org/4.14.3/Classification/index.html) package.

**Comment by amiltonwong** [comment]
OK, got it.
Is it a trained model using tensorflow package?

**Comment by WeixiaoGao** [comment]
No, just [CGAL classification](https://doc.cgal.org/4.14.3/Classification/index.html) package.

**Comment by amiltonwong** [comment]
Thanks
