### ISSUE TITLE
fail to sample the point cloud

### ISSUE THREAD

**Issue by unMajorce** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#10]
Hi:
I am trying to run the competited methods follow the step of #2 . I running the Generate_semantic_sampled_points mode, and accept following error:
![image](https://user-images.githubusercontent.com/69702677/171206229-62d889ee-5ed8-4480-a98d-fcc63b5a64de.png)
It seems that the point cloud files are not generated correctly.
Why is it happen?

**Comment by WeixiaoGao** [comment]
Thank you for your question. There was indeed a small bug that I hadn't noticed when I was cleaning up the code. It has now been fixed. Please make sure that you have set 'processing_mode = 1', and 'sampling_strategy_*** = 3' for run the competited methods.
