### ISSUE TITLE
convert binary_little_endian to ascii

### ISSUE THREAD

**Issue by ziwenjie** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#12]
Hi, authors:
The outputs of classification are in binary_little_endian 1.0, and the format is unfriendly to read and get the information.
I used the open3d to transform format, but it loses the texture map and classification.
![Screenshot from 2022-06-12 22-08-51](https://user-images.githubusercontent.com/49607231/173237233-4a5c5e76-e5b7-47b0-ab82-013a06d88916.png)

How to convert the binary_little_endian to ascii?
Thanks!
Yours, sincerely.

**Comment by WeixiaoGao** [comment]
Hi, I have just updated the code for writing ply in ascii. You can simply add 'use_binary = false' in the 'config.txt'.
