### ISSUE TITLE
How to configure 3rd_party libraries pathes?

### ISSUE THREAD

**Issue by ghost** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#13]
Hi authors! I have built boost_numpy and tbb using "cmake .." and "make" commands, and both of them can be found. I'm not clear how to "configure the CMake of SUMS with the paths of the all required packages". I tried to use "mkdir build && cd build, cmake .. commands, but when I build python_parsing package, it cann't find easy_3d, shows "python_parsing.cpp:10:10: fatal error: easy3d/surface_mesh.h: No such file or directory" error.
Thanks! Any help will be appreciate!

**Comment by WeixiaoGao** [comment]
So first you need to use CMake to configure and generate the 'semantic_urban_mesh_segmentation' project which enables 'python_parsing' to find the easy3d, then open the generated project you will find the 'python_parsing' and at there you can build it, then build the 'semantic_urban_mesh_segmentation' project.
