### ISSUE TITLE
The segments format is still all binary_little_endian, and the segments can not open in meshlab.

### ISSUE THREAD

**Issue by Yangliangzhe** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#14]
Hi, authors:
I try to use meshlab to open segments, but it failed. And I found the segments is still all in binary_little_endian format.
How to get the ascii format segment. 
Why can't the segment be openned by  meshlab.

Yours!
Best regards!
Yang

**Comment by WeixiaoGao** [comment]
Hi Yang,

Thank you for your interest in our project. Currently, Meshlab does not support binary_little_endian format. However, you can use [Mapple](https://github.com/LiangliangNan/Easy3D/releases) to visualize it.

**Comment by Yangliangzhe** [comment]
Thanks for your reply.
If I use Mapple to visualize it, how can I get the fixed angle snapshot of the segments.

Yours!
Best regard!
Yang

**Comment by WeixiaoGao** [comment]
There is a snapshot function in Mapple that allows you to do it. The icon of it is a camera.

**Comment by Yangliangzhe** [comment]
Hi, Author,

Thank you from the bottom of ma heart! 
I can visualize mesh by using Mapple.
How to take the snapshot of the Original and Segment of the same urban mesh with the same angle.
like picture of the paper.
<img width="400" alt="46d3fb1e28d1ce64a3c9d1603ed0847" src="https://user-images.githubusercontent.com/64820314/219004651-402c89cf-3558-43c8-810f-f7c815d7cf8d.png">


Best regard!

**Comment by WeixiaoGao** [comment]
Mapple snapshot can save the camera state, so you just need to restore it. Please check the Camera tab menu of it.

**Comment by ziwenjie** [comment]
> Mapple snapshot can save the camera state, so you just need to restore it. Please check the Camera tab menu of it.

You are right！ But Mapple maybe can not visualize urban mesh with its texture,

**Comment by WeixiaoGao** [comment]
No, that's not true. Mapple can be used to visualize the texture.

**Comment by ziwenjie** [comment]
> 

Hi, thanks for your reply!
I try my best to use any function of Mapple, but I can not visualize the mesh with its texture!
Could you tell me how to visualize the mesh with its texture by using Mapple， just like following picture.
<img width="182" alt="屏幕截图 2023-02-16 162953" src="https://user-images.githubusercontent.com/49607231/219310003-6eb3db63-738e-416e-b055-caec4b5f1a22.png">
Thank you from the bottom of my heart!

**Comment by WeixiaoGao** [comment]
I am using an older version of Mapple that has a texture renderer. For this function in the newer versions, you can check the git repository for Mapple.

**Comment by ziwenjie** [comment]
> I am using an older version of Mapple that has a texture renderer. For this function in the newer versions, you can check the git repository for Mapple.

You are right, Thank you very much!
