### ISSUE TITLE
The competing method pointnet training and testing

### ISSUE THREAD

**Issue by TX2liu** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#16]
Hi Doctor Gao:
I am interest in your work and very appreciate the source code of your `
SUMS-Semantic-Urban-Mesh-Segmentation-public`. 
The point clouds (from the mesh by the release exe)  which are applied in the competing method pointnet model, but I found the `batchsize=1` and the `CUDA OUT of MEMORY`( NVIDIA RTX 3090).  
I use the pointnet++(pointnet2_largemsg) to train the point clouds (from the mesh by the release exe), but I can not found the test code which is to product the `semantic_pointcloud` for urbanmesh.
Thus, would you help me solve these problem.
Thanks very much. I appreciate you from the bottom of my heart.
Liu.

**Comment by WeixiaoGao** [comment]
Hi, 
`eval.py` is the test code and you need to config the 'eval.yaml'. For `CUDA OUT of MEMORY` of pointnet, you can try to set `cuda: -1` in `../conf/training/default.yaml`. There might be some conflicts between the higher versions of Pytorch and torch_point3d.

**Comment by TX2liu** [comment]
> Hi, `eval.py` is the test code and you need to config the 'eval.yaml'. For `CUDA OUT of MEMORY` of pointnet, you can try to set `cuda: -1` in `../conf/training/default.yaml`. There might be some conflicts between the higher versions of Pytorch and torch_point3d.

Thanks, the eval.py can compute the result. how can I output the semantic point clouds?
Best wishes!
Liu

**Comment by WeixiaoGao** [comment]
If you have set `vis_data: [test]` in the visualization config file, you should be able to find the output point cloud in `checkpoint_dir`.
