### ISSUE TITLE
I can not get the same result of yours in the sota-methods kpconv and rf-mrf(moha)

### ISSUE THREAD

**Issue by TX2liu** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#17]
Hi, Doctor Gao:
I try many times to train and evaluate the kpconv, but the performance is so bad.
![Screenshot from 2023-06-04 14-39-18](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/134794555/ea03668c-39ad-4f2f-8ecb-37a281fa7fa1)

For rf-mrf(moha), I use the release exe you proposed to test and evaluate the result, and  the performance is so bad.
![微信图片_20230604144251](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/134794555/11cac0b3-89be-43f2-a5aa-ddbf7110af6e)

what is more, all hyperparameters keep same with yours, and I don't change it.
Thanks

**Comment by WeixiaoGao** [comment]
I can't tell what's wrong simply from these results. Have you checked the visualization results?

**Comment by WeixiaoGao** [comment]
Hi, I have updated the code for rf-mrf(moha) in v1.3, you can try it if it works better. Don't leave all the hyperparameters in the config file as default, you need to reconfigure the corresponding parameters for each method.
The evaluation code for KPConv seems to be correct. Can you check that the visualisation of the semantic point cloud output from the KPConv method is correct?

**Comment by TX2liu** [comment]
> Hi, I have updated the code for rf-mrf(moha) in v1.3, you can try it if it works better. Don't leave all the hyperparameters in the config file as default, you need to reconfigure the corresponding parameters for each method. The evaluation code for KPConv seems to be correct. Can you check that the visualisation of the semantic point cloud output from the KPConv method is correct?

Thanks for your help, You are so kind.
The rf-mrf(moha) was solved by your help. I apologize to you, The point clouds sampling_point_density was set 1.0 by me, so the result is too bad. Now, I set sampling_point_density=10 as thsi paper.
Best regard!

**Comment by TX2liu** [comment]
I found that **sampling_point_density** of the config.txt is set 1.0 or 10.0 to sample the point clouds from meshes, but the number of points has not changed.
<img width="633" alt="微信图片_20230605155647" src="https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/134794555/9c772fe2-b0d5-4120-9bbf-94c0b693a1d7">

**Comment by WeixiaoGao** [comment]
Hi, this is because I have fixed the sampling density of the sota point cloud generation. I have unfroze it in v1.3.1.

**Comment by TX2liu** [comment]
> Hi, this is because I have fixed the sampling density of the sota point cloud generation. I have unfroze it in v1.3.1.
Hi, Doctor Gao:
the output of one tile from kpconv like this:
<img width="1280" alt="kpconv" src="https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/134794555/ee9bb328-ba33-4d8c-bff4-b3dc957ea71f">
I have double checked the kpconv hyperparameter which is same with you release code.

**Comment by WeixiaoGao** [comment]
Is the semantic point cloud output directly from KPConv the same as this, and did you use all the training data? If so, I think the problem might be related to in_radius and first_subsampling_dl, and max_epoch.

**Comment by TX2liu** [comment]
Yes, the semantic point cloud output directly from KPConv the same as this. I use **all** 40 tiles training data, and the max_epoch=1000 .
Thanks, I will change the  in_radius and first_subsampling_dl.
 
![Screenshot from 2023-06-06 11-53-00](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/134794555/72f0573d-6cb1-4118-9a8d-0cdc0810c04d)
