### ISSUE TITLE
Building CGAL problem

### ISSUE THREAD

**Issue by Roy2xc** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#18]
Hello, I'm using the CGAL provided by your code, and it sames not work. 
![20230804165047](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/42893773/a21a1956-178f-4ed8-983c-bc0b64820765)

I'm very confused what's the problem, do you have any advise?

Thank you.

**Comment by WeixiaoGao** [comment]
Hi, 
Have you configured the CGAL path in CMake using the CGAL we provided? If so, please also check the boost iostreams and serialization packages.

**Comment by Roy2xc** [comment]
Thank you! That's the reason,. and now I tried to run the code, my command is :
 .\semantic_urban_mesh_segmentation.exe F:\my\SUMS-Semantic-Urban-Mesh-Segmentation-public-main\build\semantic_urban_mesh_segmentation\Release\config.txt
But the program just end without any report...

**Comment by Roy2xc** [comment]
Should I build the folders like your datasets?

**Comment by WeixiaoGao** [comment]
You only need to keep the path without the filename "config.txt" as it always stays the same. 
Yes, you need to create folders.

**Comment by Roy2xc** [comment]
Hi, Dr.Gao,
I got segments result but cannot find the prediction output... there are only some textures'jpg file in my output folder...

And another question is how to batch or packag download from the site you provide? I'm only able to download them one by one...

Thank you for your reply!

**Comment by Roy2xc** [comment]
I mean what should i do to get the final result? It seems i finally got a intermediate results of segments rather than predictions.

**Comment by Roy2xc** [comment]
I set the mode to "Test_config" and get a fairly good result, but it still cannot do batch operation, only the first file in the folder was processed。

**Comment by WeixiaoGao** [comment]
Hi, 
If you put your data correctly in the input folder (*.ply with *.jpg), the program will find and process all files there. You also need to make sure the type of folder in the `config.txt ` is turned on like  `process_train = true `. You can use some batch link download tools to download all folders and files.
