### ISSUE TITLE
Issue with semantic_urban_mesh_segmentation.exe: Program Stops After Reading Configuration File

### ISSUE THREAD

**Issue by Berlin000000** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#19]
Dear Dr. Gao,

Hello! I encountered an issue while running semantic_urban_mesh_segmentation.exe: the program failed to start processing the data. After the command line output "Reading configuration file:", the program stopped running abruptly. 
![image](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/48549786/d6b81fc8-5562-44ca-b687-f0f24fd0fcf8)

Could this be related to an issue with my data path? Here is the structure of my context directory:
![image](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/48549786/a38e1e4b-e807-4129-a775-f0c404caaed8)

![image](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/48549786/fcadc730-9651-490a-a460-f444365ea493)

Additionally, I've provided the modified sections of my config.txt file below:
![image](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/48549786/6116745b-5e8b-49e2-91d1-68cd4a74e002)
I would greatly appreciate your assistance in resolving this matter! Thank you for your help!

**Comment by WeixiaoGao** [comment]
Hi, the problem is related to your path. I think after *.exe it should be ". \context\". Or you can try the absolute path. B.t.w., seg_aug_py_path is only for the path to the seg_aug.py file.

**Comment by Berlin000000** [comment]
I tried the absolute path and modified seg_aug_py_path, but it still failed to run successfully. Could you kindly consider any other potential solutions to this problem?
Thank you for your help!
![Snipaste_2024-04-20_21-40-36](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/assets/48549786/f4311106-d490-4834-befe-5341afb1ff57)

**Comment by WeixiaoGao** [comment]
It's possible that the issue lies with the placement of your data. Ensure that the ply file is located directly under the 'predict' folder without any subfolders.

**Comment by Berlin000000** [comment]
Thank you very much for your assistance.

**Comment by zwl995** [comment]
> 非常感谢您的帮助。

Have you solved it? I encountered the same problem. Can you tell me what caused it?
