### ISSUE TITLE
about 4.4. Evaluation of competition methods in SUM paper

### ISSUE THREAD

**Issue by amiltonwong** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#2]
Hi, authors,

Thanks for releasing the package. How could we perform the steps for task in Section 4.4. Evaluation of competition methods in SUM paper. It is found that the competing methods are listed [here](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/tree/main/competing_methods). Could you list the steps on how to produce the evaluation results, e.g. dataset pre-processing, training, and testing.

Thanks~

**Comment by WeixiaoGao** [comment]
Hi, here are the steps to test and evaluate on competing methods:
1. Set 'operating_mode = Generate_semantic_sampled_points' in configuration file to generate sampled point clouds.
2. Copy the sampled pointcloud from '/sota/xxx_method/sampled_pointcloud/' to the corresponding folder of the competing method.
3. Run the competing method (Train and Test)
4. After you got the results from the competing method, copy them to the 'data/sota/xxx_method/semantic_pointlcoud/'
5. Then you set 'operating_mode = Evaluation_SOTA', 'processing_mode = 1', and set other configurations in 'SOTA : all deep learning methods' for the corresponding method.
6. After finishing the processing, you can find all the evaluation results in 'data/sota/xxx_method/evaluation/'

Kind regards

**Comment by amiltonwong** [comment]
@WeixiaoGao ,

Thanks for your reply. Which OS should I use to build this package? Windows/MacOS/Ubuntu?

**Comment by WeixiaoGao** [comment]
As stated in the readme, we have only tested it on Windows.
