### ISSUE TITLE
About the competing method "RF_MRF"

### ISSUE THREAD

**Issue by amiltonwong** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#3]
Hi, authors,

According to the competing methods mentioned in your paper, the RF_MRF method is used for the performance comparison. But I couldn't find it in the folder [competing_methods](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/tree/main/competing_methods). Could you release it or point me to where I could download it?

Thanks~

**Comment by WeixiaoGao** [comment]
Please carefully check [Operation modes](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#operation-modes) in the README, the 'Moha_Verdi_SOTA_pipeline' is RF_MRF.
