### ISSUE TITLE
miss the declared

### ISSUE THREAD

**Issue by ziwenjie** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#4]
Hi:
I run the semantic-urban-mesh-segmentation code in linux, and found these errors:
`char szDrive[_MAX_DRIVE], szDir[_MAX_DIR], szFname[_MAX_FNAME], szExt[_MAX_EXT];`
error: '_MAX_DRIVE' was not declared in this scope
`char szDrive[_MAX_DRIVE], szDir[_MAX_DIR], szFname[_MAX_FNAME], szExt[_MAX_EXT];`
error: '_MAX_DIR' was not declared in this scope

and so on.

**Comment by WeixiaoGao** [comment]
Hi, which operating system are you using?

**Comment by ziwenjie** [comment]
In ubuntu 20.04, and GCC 9.4 @WeixiaoGao 
and I find the whole project, the `_MAX_DRIVE_` only appeared twice

**Comment by WeixiaoGao** [comment]
That's the problem. Please read the README.md carefully, I have claimed that the current implementation only works with Windows 10. Of course, if you want it to work on ubuntu, you will need to update the code. And if you just want to test it, we've released the executable for Windows.

**Comment by ziwenjie** [comment]
> That's the problem. Please read the README.md carefully, I have claimed that the current implementation only works with Windows 10. Of course, if you want it to work on ubuntu, you will need to update the code. And if you just want to test it, we've released the executable for Windows.

I just want this code work on the ubuntu. However ,I am new to C++, so just ask for help.
Thanks!

**Comment by WeixiaoGao** [comment]
You may need to google or baidu the appropriate replacements for the errors shown here. The main problem is about reading the data, if you can update it to the boost filesystem I think it will work on Ubuntu too.
