### ISSUE TITLE
Run the code in windows10

### ISSUE THREAD

**Issue by ziwenjie** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#5]
which compiler do you use in windows10,
I used mingw64 8.1
and other errors

**Comment by WeixiaoGao** [comment]
We use Visual Studio 2017.

**Comment by ziwenjie** [comment]
> We use Visual Studio 2017.

I use the Visual Studio 2017 in windows, and  when I build the boost_numpy, I got many errors.
![image](https://user-images.githubusercontent.com/49607231/163306960-437617b7-66bf-4c81-86ad-6c654d9557bd.png)

**Comment by ziwenjie** [comment]
> > We use Visual Studio 2017.
> 
> I use the Visual Studio 2017 in windows, and when I build the boost_numpy, I got many errors. ![image](https://user-images.githubusercontent.com/49607231/163306960-437617b7-66bf-4c81-86ad-6c654d9557bd.png)

And when i build the python_parsing, it got some errors.
![image](https://user-images.githubusercontent.com/49607231/163345430-f88da11f-61a7-4d16-97b4-f8b756271391.png)

**Comment by ziwenjie** [comment]
when I build the python_parsing
 I got many errors. like belows .
![image](https://user-images.githubusercontent.com/49607231/163352006-7cb9efc2-3ed6-43ce-94f3-3bb8a2d0938a.png)

I  use the Visual Studio 2017 compiler in windows10 too.

**Comment by WeixiaoGao** [comment]
Have you used the boost_numpy we provide and do you get errors when configuring and generating your project? We have only tested it on Python 3.7 and I am not sure which version may not work. For python_parsing, you must first make sure that your boost_numpy has been built successfully. And please follow the instructions in the readme to build from the source code.

**Comment by ziwenjie** [comment]
> Have you used the boost_numpy we provide and do you get errors when configuring and generating your project? We have only tested it on Python 3.7 and I am not sure which version may not work. For python_parsing, you must first make sure that your boost_numpy has been built successfully. And please follow the instructions in the readme to build from the source code.

I used the boost_numpy provided by you, and I used the python version is 3.7.4， I can configure and generate successfully, and but when I used VS2017 to install, it got many errors. However, the code can product the boost_numpy.lib.
![image](https://user-images.githubusercontent.com/49607231/163405922-e6d23266-e96a-417f-b15c-4a3bc3e0a2bd.png)

**Comment by ziwenjie** [comment]
I found that in `..\3rd_party\python_parsing\py_aug\`, which fold had the libpp.pyd.
And I follow the Readme from start to finish.

**Comment by WeixiaoGao** [comment]
If you can successfully generate boost_numpy.lib in Release mode, it should be fine. You can try to use 'libpp.pyd' directly, otherwise, you need to generate your own 'python_parsing.dll'.

**Comment by ziwenjie** [comment]
Hi:
I meet a hard problem, I install boost successfully,
and but  always got the problem `Could NOT find Boost (missing: python3) (found version "1.78.0")`. I try many versions of boost, the problem always exist.
![image](https://user-images.githubusercontent.com/49607231/163747992-52420807-f8a8-4120-bbc2-69f1a761864d.png)

**Comment by ziwenjie** [comment]
Hi:
I am sorry for asking so many questions.
I am new to C++, and I got some new error or problem. 
I follow the Readme from start to end.
![image](https://user-images.githubusercontent.com/49607231/163807272-05ca3d1b-01fe-4183-b1ab-5bf9de132e58.png)

**Comment by ziwenjie** [comment]
> > Have you used the boost_numpy we provide and do you get errors when configuring and generating your project? We have only tested it on Python 3.7 and I am not sure which version may not work. For python_parsing, you must first make sure that your boost_numpy has been built successfully. And please follow the instructions in the readme to build from the source code.
> 
> I used the boost_numpy provided by you, and I used the python version is 3.7.4， I can configure and generate successfully, and but when I used VS2017 to install, it got many errors. However, the code can product the boost_numpy.lib. ![image](https://user-images.githubusercontent.com/49607231/163405922-e6d23266-e96a-417f-b15c-4a3bc3e0a2bd.png)

I have resolve the boost_numpy toolkit.
