### ISSUE TITLE
can not open ply file

### ISSUE THREAD

**Issue by ziwenjie** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#6]
Hi:
When I run the `.\semantic_urban_mesh_segmentation.exe [path to config.txt]` in Pipeline, and using the data_demo, I use the "Windows_binary" you provide.
Hi:
I got the error
```
 --------------------- RF Test data evaluation ---------------------
        Get all test data.
        Done in (s): 0.000398

loading RF test result : Tile_+1991_+2693
Reading testing mesh: Tile_+1991_+2693
RPly: Unable to open file
failed to open ply file 'D:/Dataset/data_demo/output/test/Tile_+1991_+2693_mesh_classification.ply'
reading file failed (no data exist)
File loading failed`
I find the file in .../test/batch_0/Tile_+1991_+2693_mesh_classification.ply.
```
Thanks.

**Comment by WeixiaoGao** [comment]
It seems that you have turned on the 'use_batch_processing_on_xxx' mode, turn it to false in config.txt. And better use the demo data from 'main' repository.

**Comment by ziwenjie** [comment]
> It seems that you have turned on the 'use_batch_processing_on_xxx' mode, turn it to false in config.txt. And better use the demo data from 'main' repository.

Thanks for your reply.
But I am make the 'use_batch_processing_on_xxx' in **false** mode, and I turn on the ‘use_batch_processing_on_xxx’ mode， it still appear the error.
Sincerely yours.

**Comment by PeppaBear** [comment]
I also have the same question

> Hi,authors: 
I have the same issue about it.

**Comment by WeixiaoGao** [comment]
The problem is in config.txt, and I just updated it to the correct setting in the demo data. Specifically, the batch parameter 'save_textures_in_predict' should equal false when not executed in batch mode, otherwise it will allow overwriting the output path. So now the problem should be solved.

**Comment by ziwenjie** [comment]
Thank you very much for your reply.
Sincerely!
