### ISSUE TITLE
How to load you model to segment unlabel data

### ISSUE THREAD

**Issue by z-chw** [tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public#8]
Hi, authors:
I found that
``` 
Data without labels
For unlabelled urban scene mesh data, you can use our [trained model]
````
However, I do not know how to  use your `SUMS_Win10_binary_v1.0` to load your model to segment our own unlabel urban mesh data.

**Comment by WeixiaoGao** [comment]
You can just put the trained model in the 'model' folder,  your data in the 'input/predict/', and set operating_mode = Test_config in the config.txt, then it should work.
